### ISSUE TITLE
How can i start msfconsole

### ISSUE THREAD

**Issue by mshaheerz** [noob-hackers/m-wiz#14]
Installed successfully how to start msconsol commant not found pleas replay

**Comment by chipsetdev** [comment]
cd metasploit-framwork && ./msfconsole

**Comment by infraredracoon1** [comment]
Did u install it with m-wiz and I'd recommend using Fdroid for termux and termux API because the Google version didn't work so well with my setup, at least if u have android 10 or newer. If u used m-wiz cd to metasploit-framework and ./msfconsole

**Comment by ronakjangra** [comment]
> cd metasploit-framwork && ./msfconsole

Not working
