### ISSUE TITLE
Please i can't finished please tell me 

### ISSUE THREAD

**Issue by ib774** [noob-hackers/m-wiz#16]
![Screenshot_20210610-025004_Termux.jpg](https://user-images.githubusercontent.com/85458039/121511794-b4a5d400-c9f1-11eb-9799-1e80ef78ee4d.jpg)

**Comment by infraredracoon1** [comment]
```````
pkg update && pkg upgrade
cd metasploit-framework 
 update bundler 
 gem install missing gems 
./msfconsole
``````````
## Create SQL Database:
 `````````
cd 
 pkg install postgresql 
 initdb ~/pg 
``````````
## Start the Server:
````
 pg_ctl -D ~/pg start  
````
## Replace "Your_Username" below with whatever username you want  
`````````
createuser -P -s -e  Your_Username 
`````````
### Replace "Your_Database" below with whatever you want:
````
createdb -O  Your_Username Your_Database 
````
## Login to your SQL database
`````
 psql -U  Your_Username -d Your_Database 
`````
