### ISSUE TITLE
Unable to install metasploit on phone

### ISSUE THREAD

**Issue by learnthetech** [noob-hackers/m-wiz#20]
Hi, It's showing for an error. Couldn't find rake-13.0.3

please help me to solve this!
![WhatsApp Image 2021-12-05 at 8 07 13 AM](https://user-images.githubusercontent.com/95562777/144738083-606d611b-1617-43c5-9e48-0fc8a9e8749f.jpeg)

**Comment by arungeeky** [comment]
I also have the same prblm how to solve dis plz explain
