### ISSUE TITLE
Issue in metasploit

### ISSUE THREAD

**Issue by Yudhi-sthir** [noob-hackers/m-wiz#23]
![Screenshot_2022-03-02-22-19-14-588_com termux](https://user-images.githubusercontent.com/79323086/156408807-bc0e0fd5-360e-449a-8dce-936d4f510a58.jpg)

**Comment by Yudhi-sthir** [comment]
![Uploading Screenshot_2022-03-02-22-22-29-556_com.termux.jpg…]()

**Comment by subinravi8** [comment]
this same issue is with me plzzzz someone hepl

**Comment by zhengyo** [comment]
> ![截图_2022-03-02-22-19-14-588_com termux](https://user-images.githubusercontent.com/79323086/156408807-bc0e0fd5-360e-449a-8dce-936d4f510a58.jpg)

Switch to the msf directory and run" bundle install"
