### ISSUE TITLE
Hi hello


### ISSUE THREAD

**Issue by XMMCCCXLV** [noob-hackers/m-wiz#26]
I need some help with the Metasploit framework.
The problem that I encounter is when the Metasploit installation is complete and type the. /mfsconsole:
The this appeared
 bash: ./mfsconsole:: No such file or directory
The bash didn't exist, what to do?

**Comment by sohib26** [comment]
I think its not installed properly

**Comment by sohib26** [comment]
Or just type msfconsole

**Comment by sohib26** [comment]
https://youtu.be/KsQkQs8Vbhw

Or follow this one
