### ISSUE TITLE
Erro?!

### ISSUE THREAD

**Issue by Jeiel0rbit** [noob-hackers/m-wiz#28]
I didn't understand the real problem. My device is Android 11. Would it be something to add?

![Screenshot_20220627-175452.png](https://user-images.githubusercontent.com/72875404/176034698-7e1c16f1-2cf4-42a8-b6a4-7340f72dbdbe.png)

```Could not find rake-13.0.3 in any of the sources
Run `bundle install` to install missing gems.


    ＞＞＞＞＞＞＞＞＞ [EXIT] ＜＜＜＜＜＜＜＜＜```

**Comment by gokulrengaraj** [comment]
yes i to had a same problem is there any solution ?
